# Generated by Django 4.2.7 on 2024-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_alter_usuario_is_active_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(help_text='esta activo', verbose_name='is_active'),
        ),
    ]
