# Generated by Django 4.1.5 on 2023-02-13 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eve', '0003_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad_Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('descripcion_modalidad_asistencia', models.CharField(max_length=20, unique=True, verbose_name='modalidad asistencia')),
                ('color_modalidad_asistencia', models.CharField(max_length=10)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modalidad de asistencia',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('descripcion_tipo_participante', models.CharField(max_length=30, unique=True, verbose_name='tipo participante')),
                ('background_tipo_participante', models.CharField(max_length=10)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipo de participantes',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nombre_participante', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_participante', models.CharField(max_length=50, verbose_name='apellido')),
                ('asistio_evento', models.BooleanField(default=False, verbose_name='Asistio')),
                ('confirmo_asistencia', models.BooleanField(default=True, verbose_name='Confirmo asistencia')),
                ('email_participante', models.EmailField(max_length=100, verbose_name='cuenta correo')),
                ('telefono_participante', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('empresa_participante', models.CharField(blank=True, max_length=150, verbose_name='empresa')),
                ('cargo_participante', models.CharField(blank=True, max_length=150, verbose_name='cargo')),
                ('observaciones_participante', models.CharField(blank=True, max_length=250, verbose_name='observaciones')),
                ('acompanante_de', models.CharField(blank=True, max_length=100, verbose_name='acompañante de')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eve.evento')),
                ('modalidad_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='par.modalidad_asistencia')),
                ('tipo_participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='par.tipo_participante')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
