# Generated by Django 4.2.7 on 2023-11-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='modalidad_asistencia',
            name='descripcion_modalidad_asistencia',
            field=models.CharField(help_text='Modalidad de Asistencia', max_length=20, unique=True),
        ),
        
       
    ]
