# Generated by Django 4.2.7 on 2023-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0002_remove_tipo_participante_credencial_tipo_participante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_participante',
            name='tipo_identificacion_participante',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
