# Generated by Django 4.2.7 on 2023-12-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0003_tipo_participante_tipo_identificacion_participante'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['evento'], name='par_partici_evento__c3492e_idx'),
        ),
    ]
