# Generated by Django 4.2.7 on 2024-02-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve', '0006_evento_nuevo_tipo_participante'),
        ('par', '0008_participante_codigo_qr_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='participante',
            name='evento_qr_idx',
        ),
        migrations.AlterIndexTogether(
            name='participante',
            index_together={('evento', 'codigo_qr')},
        ),
    ]
