# Generated by Django 4.2.7 on 2024-02-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0009_remove_participante_evento_qr_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo_qr',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='codigo qr'),
        ),
    ]
