# Generated by Django 4.2.7 on 2024-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0014_alter_participante_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_qr', None), _negated=True), fields=('evento', 'codigo_qr'), name='evento_qr_unico'),
        ),
    ]
