# Generated by Django 4.2.7 on 2024-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0016_participante_par_partici_evento__15baf8_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participante',
            name='evento_qr_unico',
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('asistio_evento', True)), fields=('evento', 'codigo_qr'), name='evento_qr_unico'),
        ),
    ]
