# Generated by Django 4.2.7 on 2024-02-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0018_alter_participante_codigo_qr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participante',
            name='evento_qr_unico',
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_qr', None), _negated=True), fields=('evento', 'codigo_qr'), name='evento_qr_unico'),
        ),
    ]
