# Generated by Django 4.2.7 on 2024-02-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0020_alter_participante_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo_qr',
            field=models.CharField(blank=True, default='Sin QR', max_length=100, null=True, verbose_name='codigo qr'),
        ),
    ]
