# Generated by Django 4.2.7 on 2024-02-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0023_alter_participante_codigo_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='participante',
            name='evento_qr_unico',
        ),
        migrations.RemoveIndex(
            model_name='participante',
            name='par_partici_evento__15baf8_idx',
        ),
    ]
