# Generated by Django 4.2.7 on 2024-02-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0025_alter_participante_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participante',
            new_name='par_evento_qr_unico',
            old_name='par_partici_evento__15baf8_idx',
        ),
    ]
