# Generated by Django 4.2.7 on 2024-03-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0026_rename_par_partici_evento__15baf8_idx_par_evento_qr_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo_qr',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='codigo qr'),
        ),
    ]
