# Generated by Django 4.2.7 on 2024-03-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0030_alter_participante_codigo_qr'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['evento', 'codigo_qr'], name='idx_par_evento_qr_unico'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_qr', None), _negated=True), fields=('evento', 'codigo_qr'), name='const_evento_qr_unico'),
        ),
    ]
