# Generated by Django 4.2.7 on 2024-01-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve', '0004_usuario_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='modalidad_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eve.modalidad_evento'),
        ),
    ]
