# Generated by Django 4.2.7 on 2024-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve', '0006_evento_nuevo_tipo_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asigna_qr_registro',
            field=models.BooleanField(default=False, verbose_name='Se asigna QR al registrarse'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imprime_etiqueta_registro',
            field=models.BooleanField(default=False, verbose_name='Se imprime etiqueta al registrarse'),
        ),
    ]
